// <auto-generated />
using System;
using Cadastro_Petshop.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cadastro_Petshop.Migrations
{
    [DbContext(typeof(Cadastro_PetshopContext))]
    partial class Cadastro_PetshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cadastro_Petshop.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Castrado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("int");

                    b.HasKey("AnimalID");

                    b.HasIndex("PlanoId");

                    b.ToTable("TB_Animal");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.AnimalVeterinario", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("AnimalId", "VeterinarioId", "Data");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("TB_AnimalVeterinario");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.ContratoTrabalho", b =>
                {
                    b.Property<int>("ContratoTrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("Date")
                        .HasColumnName("Dt_Contratacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContratoTrabalhoId");

                    b.ToTable("TB_ContratoTrabalho");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Plano", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanoId");

                    b.ToTable("TB_Plano");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Veterinario", b =>
                {
                    b.Property<int>("VeterinarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoTrabalhoId")
                        .HasColumnType("int");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("VeterinarioId");

                    b.HasIndex("ContratoTrabalhoId");

                    b.ToTable("TB_Veterinario");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Animal", b =>
                {
                    b.HasOne("Cadastro_Petshop.Models.Plano", "Plano")
                        .WithMany("Animais")
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.AnimalVeterinario", b =>
                {
                    b.HasOne("Cadastro_Petshop.Models.Animal", "Animal")
                        .WithMany("AnimaisVeterinarios")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadastro_Petshop.Models.Veterinario", "Veterinario")
                        .WithMany("AnimaisVeterinarios")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Veterinario", b =>
                {
                    b.HasOne("Cadastro_Petshop.Models.ContratoTrabalho", "ContratoTrabalho")
                        .WithMany()
                        .HasForeignKey("ContratoTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContratoTrabalho");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Animal", b =>
                {
                    b.Navigation("AnimaisVeterinarios");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Plano", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("Cadastro_Petshop.Models.Veterinario", b =>
                {
                    b.Navigation("AnimaisVeterinarios");
                });
#pragma warning restore 612, 618
        }
    }
}
